/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var g2 = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[2,10],$V1=[1,18],$V2=[1,31],$V3=[1,32],$V4=[1,33],$V5=[1,34],$V6=[1,35],$V7=[1,36],$V8=[1,37],$V9=[1,38],$Va=[1,39],$Vb=[1,40],$Vc=[18,23,43,44,45,47,49,51,53,55,57,59];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"s":3,"inicio":4,"EOF":5,"HTMLA":6,"contenidohtml":7,"HTMLC":8,"head":9,"body":10,"HEADA":11,"contenidohead":12,"HEADC":13,"TITLEA":14,"contenidotitle":15,"TITLEC":16,"IDENTIFICADOR":17,"MENOR":18,"RBODY":19,"atributosbodydiv":20,"MAYOR":21,"contenidobody":22,"BODYC":23,"RSTYLE":24,"IGUAL":25,"DOSP":26,"color":27,"RYELLOW":28,"RGREEN":29,"RBLUE":30,"RRED":31,"RWHITE":32,"RSKYBLUE":33,"lcontenido":34,"div":35,"br":36,"p":37,"hs":38,"button":39,"label":40,"input":41,"RDIV":42,"DIVC":43,"RBR":44,"RPA":45,"RPC":46,"H1A":47,"H1C":48,"H2A":49,"H2C":50,"H3A":51,"H3C":52,"H4A":53,"H4C":54,"BUTTONA":55,"BUTTONC":56,"LABELA":57,"LABELC":58,"INPUTA":59,"contenidoinput":60,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",6:"HTMLA",8:"HTMLC",11:"HEADA",13:"HEADC",14:"TITLEA",16:"TITLEC",17:"IDENTIFICADOR",18:"MENOR",19:"RBODY",21:"MAYOR",23:"BODYC",24:"RSTYLE",25:"IGUAL",26:"DOSP",28:"RYELLOW",29:"RGREEN",30:"RBLUE",31:"RRED",32:"RWHITE",33:"RSKYBLUE",42:"RDIV",43:"DIVC",44:"RBR",45:"RPA",46:"RPC",47:"H1A",48:"H1C",49:"H2A",50:"H2C",51:"H3A",52:"H3C",53:"H4A",54:"H4C",55:"BUTTONA",56:"BUTTONC",57:"LABELA",58:"LABELC",59:"INPUTA"},
productions_: [0,[3,2],[4,3],[7,2],[9,3],[12,3],[15,1],[15,0],[10,6],[20,5],[20,0],[27,1],[27,1],[27,1],[27,1],[27,1],[27,1],[22,2],[22,1],[34,1],[34,1],[34,1],[34,1],[34,1],[34,1],[34,1],[35,6],[36,1],[37,3],[38,3],[38,3],[38,3],[38,3],[39,3],[40,3],[41,1],[60,1],[60,0]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
return $$[$0-1];
break;
case 2:
this.$=API2.astHTML($$[$0-1]);
break;
case 3:
this.$=API2.contenidohtml($$[$0-1],$$[$0]);
break;
case 4:
this.$=API2.astHead($$[$0-1]);
break;
case 5:
this.$=API2.astTitle($$[$0-1]);
break;
case 6:
this.$=API2.astContenidoT($$[$0]);
break;
case 7:
this.$=API2.astContenidoT("Vacio");
break;
case 8:
this.$=API2.astBody($$[$0-3],$$[$0-1]);
break;
case 9:
this.$=API2.astAtributos($$[$0]);
break;
case 10:
this.$=API2.astSinAtributos();
break;
case 11:
this.$=COLORES.YELLOW;
break;
case 12:
this.$=COLORES.GREEN;
break;
case 13:
this.$=COLORES.BLUE;
break;
case 14:
this.$=COLORES.RED;
break;
case 15:
this.$=COLORES.WHITE;
break;
case 16:
this.$=COLORES.SKYBLUE;
break;
case 17:
$$[$0-1].push($$[$0]);  this.$ = $$[$0-1];
break;
case 18:
this.$ = [$$[$0]];
break;
case 19: case 20: case 21: case 22: case 23: case 24: case 25:
this.$=$$[$0];
break;
case 26:
this.$=API2.astDiv($$[$0-3],$$[$0-1]);
break;
case 27:
this.$=API2.astBr();
break;
case 28:
this.$=API2.astP($$[$0-1]);
break;
case 29:
this.$=API2.asth1($$[$0-1]);
break;
case 30:
this.$=API2.asth2($$[$0-1]);
break;
case 31:
this.$=API2.asth3($$[$0-1]);
break;
case 32:
this.$=API2.asth4($$[$0-1]);
break;
case 33:
this.$=API2.astbutton($$[$0-1]);
break;
case 34:
this.$=API2.astlabel($$[$0-1]);
break;
case 35:
this.$=API2.astinput("CAJA INPUT");
break;
case 36:
this.$=API2.astContenidoI($$[$0]);
break;
case 37:
this.$=API2.astContenidoI("Vacio");
break;
}
},
table: [{3:1,4:2,6:[1,3]},{1:[3]},{5:[1,4]},{7:5,9:6,11:[1,7]},{1:[2,1]},{8:[1,8]},{10:9,18:[1,10]},{12:11,14:[1,12]},{5:[2,2]},{8:[2,3]},{19:[1,13]},{13:[1,14]},{15:15,16:[2,7],17:[1,16]},{20:17,21:$V0,24:$V1},{18:[2,4]},{16:[1,19]},{16:[2,6]},{21:[1,20]},{25:[1,21]},{13:[2,5]},{18:$V2,22:22,34:23,35:24,36:25,37:26,38:27,39:28,40:29,41:30,44:$V3,45:$V4,47:$V5,49:$V6,51:$V7,53:$V8,55:$V9,57:$Va,59:$Vb},{17:[1,41]},{18:$V2,23:[1,42],34:43,35:24,36:25,37:26,38:27,39:28,40:29,41:30,44:$V3,45:$V4,47:$V5,49:$V6,51:$V7,53:$V8,55:$V9,57:$Va,59:$Vb},o($Vc,[2,18]),o($Vc,[2,19]),o($Vc,[2,20]),o($Vc,[2,21]),o($Vc,[2,22]),o($Vc,[2,23]),o($Vc,[2,24]),o($Vc,[2,25]),{42:[1,44]},o($Vc,[2,27]),{17:[1,45]},{17:[1,46]},{17:[1,47]},{17:[1,48]},{17:[1,49]},{17:[1,50]},{17:[1,51]},o($Vc,[2,35]),{26:[1,52]},{8:[2,8]},o($Vc,[2,17]),{20:53,21:$V0,24:$V1},{46:[1,54]},{48:[1,55]},{50:[1,56]},{52:[1,57]},{54:[1,58]},{56:[1,59]},{58:[1,60]},{27:61,28:[1,62],29:[1,63],30:[1,64],31:[1,65],32:[1,66],33:[1,67]},{21:[1,68]},o($Vc,[2,28]),o($Vc,[2,29]),o($Vc,[2,30]),o($Vc,[2,31]),o($Vc,[2,32]),o($Vc,[2,33]),o($Vc,[2,34]),{21:[2,9]},{21:[2,11]},{21:[2,12]},{21:[2,13]},{21:[2,14]},{21:[2,15]},{21:[2,16]},{18:$V2,22:69,34:23,35:24,36:25,37:26,38:27,39:28,40:29,41:30,44:$V3,45:$V4,47:$V5,49:$V6,51:$V7,53:$V8,55:$V9,57:$Va,59:$Vb},{18:$V2,34:43,35:24,36:25,37:26,38:27,39:28,40:29,41:30,43:[1,70],44:$V3,45:$V4,47:$V5,49:$V6,51:$V7,53:$V8,55:$V9,57:$Va,59:$Vb},o($Vc,[2,26])],
defaultActions: {4:[2,1],8:[2,2],9:[2,3],14:[2,4],16:[2,6],19:[2,5],42:[2,8],61:[2,9],62:[2,11],63:[2,12],64:[2,13],65:[2,14],66:[2,15],67:[2,16]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

	const COLORES 		= require('./asthtml').COLORES;
	const API2	= require('./asthtml').API2;
	const LERRORES2	= require('./asthtml').LERRORES2;
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-insensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
	const LERRORES2	= require('./ast').LERRORES2;

var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:// se ignoran espacios en blanco
break;
case 1:// comentario simple línea
break;
case 2:// comentario multiple líneas
break;
case 3:return 6;
break;
case 4:return 8;
break;
case 5:return 11;
break;
case 6:return 13;
break;
case 7:return 14;
break;
case 8:return 16;
break;
case 9:return 19;
break;
case 10:return 23;
break;
case 11:return 24;
break;
case 12:return 'RBACKGROUND';
break;
case 13:return 28;
break;
case 14:return 29;
break;
case 15:return 30;
break;
case 16:return 31;
break;
case 17:return 32;
break;
case 18:return 33;
break;
case 19:return 42;
break;
case 20:return 43;
break;
case 21:return 44;
break;
case 22:return 45;
break;
case 23:return 46;
break;
case 24:return 47;
break;
case 25:return 48;
break;
case 26:return 49;
break;
case 27:return 50;
break;
case 28:return 51;
break;
case 29:return 52;
break;
case 30:return 54;
break;
case 31:return 54;
break;
case 32:return 55;
break;
case 33:return 56;
break;
case 34:return 57;
break;
case 35:return 58;
break;
case 36:return 59;
break;
case 37:return 'INPUTC';
break;
case 38:return 18;
break;
case 39:return 21;
break;
case 40:return 25;
break;
case 41:return 26;
break;
case 42:return 'COMILLAD';
break;
case 43:return 17;
break;
case 44:return 5;
break;
case 45: $$ = LERRORES2.astErrores(LERRORES.astError(yy_.yytext , yy_.yylloc.first_line , yy_.yylloc.first_column, "Lexico")); LERRORES.astPrint($$);
break;
}
},
rules: [/^(?:\s+)/i,/^(?:\/\/.*)/i,/^(?:[\/][*][^*]*[*]+([^\/*][^*]*[*]+)*[\/])/i,/^(?:<html>)/i,/^(?:<\/html>)/i,/^(?:<head>)/i,/^(?:<\/head>)/i,/^(?:<title>)/i,/^(?:<\/title>)/i,/^(?:body\b)/i,/^(?:<\/body>)/i,/^(?:style\b)/i,/^(?:backgroud\b)/i,/^(?:yellow\b)/i,/^(?:green\b)/i,/^(?:blue\b)/i,/^(?:red\b)/i,/^(?:white\b)/i,/^(?:skyblue\b)/i,/^(?:div\b)/i,/^(?:<\/div>)/i,/^(?:<br>)/i,/^(?:<p>)/i,/^(?:<\/p>)/i,/^(?:<h1>)/i,/^(?:<\/h1>)/i,/^(?:<h2>)/i,/^(?:<\/h2>)/i,/^(?:<h3>)/i,/^(?:<\/h3>)/i,/^(?:<h4>)/i,/^(?:<\/h4>)/i,/^(?:<button>)/i,/^(?:<\/button>)/i,/^(?:<label>)/i,/^(?:<\/label>)/i,/^(?:<input>)/i,/^(?:<\/input>)/i,/^(?:<)/i,/^(?:>)/i,/^(?:=)/i,/^(?::)/i,/^(?:")/i,/^(?:( ?_?[a-zA-Z])[a-zA-Z0-9_]*)/i,/^(?:$)/i,/^(?:.)/i],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = g2;
exports.Parser = g2.Parser;
exports.parse = function () { return g2.parse.apply(g2, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}